# Generated by Django 5.2.11 on 2026-06-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('description', models.TextField()),
                ('number_of_players', models.IntegerField(default=0)),
                ('server_status', models.BooleanField()),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('server_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
