# Generated by Django 6.0.6 on 2026-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_profile_profile_picture_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10),
        ),
    ]
